version: "3.8"
services:
    web:
        image: lucee/lucee:5.3
        ports:
            - 80:8888
        working_dir: /var/www
        volumes:
            - ./www/:/var/www
            - ./config/server-context/password.txt:/opt/lucee/server/lucee-server/context/password.txt
            - ./config/server-context/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
            
volumes:
    lucee-test-data:
